from .home_route import home_blp
from .initialize_routes import initial_blp
from .pagination_route import pager_blp
from .quote_route import quote_blp
from .reader_routes.reader_route import reader_blp
from .excel_to_pdf_route import excel_blp
from .translation_route import translation_blp
from .mpesa_statement_route import mpesa_blp
from .ai_reader_routes import ai_blp
from .pdf_merger_route import merge_blp